project_name: waveland
release:
  github:
    owner: go-johnnyhe
    name: waveland

builds:
  - id: waveland
    main: .
    binary: waveland
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git

brews:
  - name: waveland
    tap:
      owner: go-johnnyhe
      name: homebrew-tap
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
    folder: Formula
    homepage: "https://github.com/go-johnnyhe/waveland"
    description: "A CLI tool collab coding"
    install: |
      bin.install "waveland"
